title: Hinoki
description: A Language Server Protocol implementation that provides features like autocomplete, go to definition, find all references, and more for BrightScript.
baseurl: "/hinoki"
url: https://willowtreeapps.github.io
twitter_username: willowtreeapps
github_username:  willowtreeapps
markdown: kramdown
includes_dir: resources/_includes
layouts_dir: resources/_layouts
sass:
  sass_dir: resources/_assets/stylesheets
  style: compressed
logo: hinoki-logo
